version: "3.8"

services:
  web-app:
    image: tripletri/zenithar-web
    ports:
      - "8122:80"
    environment:
      ProductsClient__ApiUri: http://products-api
    depends_on:
      - products-api
  
  products-api:
    image: tripletri/zenithar-products
    ports:
      - "8123:80"
    environment:
      Postgres__ConnectionString: Host=postgres;Port=5432;Database=zenithar;Username=postgres;Password=pg_pass
      DbStartUp__Seed: true
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: zenithar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_pass
    ports:
      - "5432:5432"