name: ci

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: echo "Building images. Tag number is $env:GITHUB_RUN_NUMBER"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push products-api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/products-api.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zenithar/products:latest ${{ secrets.DOCKERHUB_USERNAME }}/zenithar/products:${{ github.run.number }}

      - name: Build and push web-app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/web-app.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zenithar/web:latest ${{ secrets.DOCKERHUB_USERNAME }}/zenithar/web:${{ github.run.number }}
