name: ci

on:
  push:
    branches: [ main ]

env:
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: echo "Building images. Images tag is $IMAGE_TAG"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker products-meta
        id: products-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/zenithar-products
            cr.yandex/${{vars.YANDEX_REGISTRY_ID}}/zenithar-products
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }} 
            
      - name: Docker web-meta
        id: web-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/zenithar-web
            cr.yandex/${{vars.YANDEX_REGISTRY_ID}}/zenithar-web
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to Yandex Registry
        uses: docker/login-action@v2
        with: 
          registry: cr.yandex
          username: json_key 
          password: ${{ secrets.YANDEX_REGISTRY_SVC_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push products
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/products-api.dockerfile
          push: true
          tags: ${{ steps.products-meta.outputs.tags }}
          labels: ${{ steps.products-meta.outputs.labels }}

      - name: Build and push web
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/web-app.dockerfile
          push: true
          tags: ${{ steps.web-meta.outputs.tags }}
          labels: ${{ steps.web-meta.outputs.labels }}
