name: ci

on:
  push:
    branches: [ main ]

env:
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: echo "Building images. Images tag is $IMAGE_TAG"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push products
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/products-api.dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/zenithar-products:latest , ${{ vars.DOCKERHUB_USERNAME }}/zenithar-products:${{ env.IMAGE_TAG }}

      - name: Build and push web
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/web-app.dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/zenithar-web:latest , ${{ vars.DOCKERHUB_USERNAME }}/zenithar-web:${{ env.IMAGE_TAG }}
